#!/bin/bash -efu

if [[ -n "${VAGRANT_LOG:-}" ]]; then
  set -x
fi

cmd="$1"; shift
case "$cmd" in
  run-instance)
    image="$1"; shift
    cmd_bootstrap="$(which qemu-docker-$image 2>&- || true)"
    if [[ -x "$cmd_bootstrap" ]]; then
      $cmd_bootstrap
    fi
    docker run ${DOCKER_OPT:--privileged -n -d -w /root -h "$(basename "$(pwd)")" }"$image" "$@"
    ;;
  terminate-instance)
    instance="$1"; shift
    docker stop "$instance" 
    ;;
  ssh-info)
    instance="$1"; shift
    echo "$(docker inspect -format '{{.NetworkSettings.IPAddress}}' $instance)" 22
    ;;
  read-state)
    instance="$1"; shift
    case "$(docker inspect -format '{{.State.Running}}' $instance)" in
      true)
        echo running
        ;;
      *)
        echo not_created
        ;;
    esac
    ;;
  *)
    exit 1
    ;;
esac
